name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
           # Options
          user: eroten
          template: classic
          base: header, activity, community, repositories, metadata
          
          config_animations: yes
          config_timezone: America/New_York
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          
          plugin_habits: yes
          plugin_habits_from: 250
          plugin_habits_days: 90
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_rss: yes
          plugin_rss_source: https://lizroten.com/index.xml  # RSS feed
          plugin_rss_limit: 6                                  # Limit to 6 items          
